from sofalite.conf.misc import PLATFORM
from sofalite.utils import paths

LOCAL_PATH = paths.get_local_path(PLATFORM)
INTERNAL_FPATH = LOCAL_PATH / '_internal'
DATABASE_FPATH = INTERNAL_FPATH / 'sofalite.db'
INTERNAL_REPORT_FPATH = INTERNAL_FPATH / 'reports'
INTERNAL_REPORT_CSS_FPATH = INTERNAL_REPORT_FPATH / 'css'
INTERNAL_REPORT_JS_FPATH = INTERNAL_REPORT_FPATH / 'js'
INTERNAL_REPORT_IMG_FPATH = INTERNAL_REPORT_FPATH / 'img'
